### ISSUE TITLE
Can't be compiled on Windows !

### ISSUE THREAD

**Issue by bcashier** [fede1024/rust-rdkafka#137]
Hi,

I can't get Kafka compiled and installed on my PC:

> - Windows 7 64bit
> - Rust: rustup 1.18.3 (435397f48 2019-05-22) - Stable
> - Cargo: cargo 1.36.0 (c4fcfb725 2019-05-15)

Trying to use crate: `rdkafka = "~0.21"`

Each time I am trying to compile my program, I am getting this error message:

```
error: failed to run custom build command for `rdkafka-sys v1.0.0`

Caused by:
  process didn't exit successfully: `C:\Users\Ruster\Desktop\target\debug\build\rdkafka-sys-1509f48374dd51bd\build-script-build` (exit code: 101)
--- stdout
Configuring librdkafka

--- stderr
Building and linking librdkafka statically
Running command: "./configure --disable-sasl --disable-ssl --disable-lz4" in dir: librdkafka
thread 'main' panicked at 'Command failed with error: The system cannot find the file specified. (os error 2)', C:\Users\Rsuter\.cargo\registry\src\github.com-1ecc6299db9ec823\rdkafka-sys-1.0.0\build.rs:25:21
stack backtrace:
   0: std::sys_common::backtrace::_print
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\sys_common\backtrace.rs:71
   1: std::panicking::default_hook::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:197
   2: std::panicking::default_hook
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:211
   3: std::panicking::rust_panic_with_hook
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:474
   4: std::panicking::continue_panic_fmt
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:381
   5: std::panicking::begin_panic_fmt
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:336
   6: build_script_build::run_command_or_fail
             at .\build.rs:25
   7: build_script_build::build_librdkafka
             at .\build.rs:109
   8: build_script_build::main
             at .\build.rs:61
   9: std::rt::lang_start::{{closure}}<()>
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\src\libstd\rt.rs:64
  10: std::panicking::try::do_call<closure,i32>
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:293
  11: panic_unwind::__rust_maybe_catch_panic
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libpanic_unwind\lib.rs:85
  12: std::rt::lang_start_internal
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\rt.rs:48
  13: std::rt::lang_start<()>
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\src\libstd\rt.rs:64
  14: main
  15: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  16: BaseThreadInitThunk
  17: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
error: build failed
```

How this issue can be solved please ? Really need to integrate Kafka inside my program.

Thank you in advance.

**Comment by moh-abk** [comment]
@bcashier 

I had thesame issue on Mac. Digging into https://github.com/fede1024/rust-rdkafka/blob/master/rdkafka-sys/build.rs cargo run works correctly when i set the CARGO_FEATURE_DYNAMIC_LINKING env var

**Comment by bcashier** [comment]
@moh-abk Thank you for your answer sir :)

Can you show me how to set the CARGO_FEATURE_DYNAMIC_LINKING env var ?

Give me the right steps you used to set it on MAC so I can replay the same for Windows if possible.

Waiting your answer, thanks again.
