### ISSUE TITLE
The build is failing on macOS Catalina

### ISSUE THREAD

**Issue by a-rodin** [fede1024/rust-rdkafka#159]
```sh
% RUST_BACKTRACE=1 cargo build
   Compiling rdkafka-sys v1.0.1 (/private/tmp/rust-rdkafka/rdkafka-sys)
error: failed to run custom build command for `rdkafka-sys v1.0.1 (/private/tmp/rust-rdkafka/rdkafka-sys)`

Caused by:
  process didn't exit successfully: `/private/tmp/rust-rdkafka/rdkafka-sys/target/debug/build/rdkafka-sys-b9d664ac519f234d/build-script-build` (exit code: 101)
--- stdout
Configuring librdkafka
using cache file config.cache
checking for OS or distribution... ok (osx)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok (cached)
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok (cached)
checking executable ld... ok (cached)
checking executable nm... ok (cached)
checking executable objdump... ok (cached)
checking executable strip... ok (cached)
checking for debug symbols compiler flag (-g...)... ok (cached)
checking for pkgconfig (by command)... failed
checking for install (by command)... failed
checking for PIC (by compile)... ok (cached)
checking for GNU-compatible linker options... failed
checking for OSX linker options... ok (cached)
checking for GNU linker-script ld flag... failed
checking for Solaris linker-script ld flag... failed (ignore)
checking for __atomic_32 (by compile)... ok (cached)
checking for __atomic_64 (by compile)... ok (cached)
checking for socket (by compile)... ok (cached)
parsing version '0x010001ff'... ok (1.0.1)
checking for librt (by compile)... failed
checking for libpthread (by compile)... ok (cached)
checking for c11threads (by compile)... failed (disable)
checking for libdl (by compile)... ok (cached)
checking for zlib (by compile)... ok (cached)
checking for zstd (by compile)... failed (disable)
checking for libm (by compile)... ok (cached)
checking for rapidjson (by compile)... failed (disable)
checking for crc32chw (by compile)... ok (cached)
checking for regex (by compile)... ok (cached)
checking for strndup (by compile)... ok (cached)
checking for strerror_r (by compile)... ok (cached)
checking for pthread_setname_gnu (by compile)... failed (disable)
checking for nm (by env NM)... ok (cached)
Generated Makefile.config
Generated config.h

Configuration summary:
  prefix                   /usr/local
  MKL_DISTRO               osx
  SOLIB_EXT                .dylib
  ARCH                     x86_64
  CPU                      generic
  GEN_PKG_CONFIG           y
  ENABLE_SSL               n
  ENABLE_GSSAPI            n
  ENABLE_DEVEL             n
  ENABLE_VALGRIND          n
  ENABLE_REFCNT_DEBUG      n
  ENABLE_SHAREDPTR_DEBUG   n
  ENABLE_LZ4_EXT           n
  MKL_APP_NAME             librdkafka
  MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
  CC                       gcc
  CXX                      g++
  LD                       ld
  NM                       nm
  OBJDUMP                  objdump
  STRIP                    strip
  CPPFLAGS                 -gstrict-dwarf -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align
  PKG_CONFIG               pkg-config
  INSTALL                  install
  LIB_LDFLAGS              -shared -dynamiclib -Wl,-install_name,$(DESTDIR)$(libdir)/$(LIBFILENAME)
  RDKAFKA_VERSION_STR      1.0.1
  MKL_APP_VERSION          1.0.1
  LIBS                     -lm -lz -ldl -lpthread
  CXXFLAGS                 -Wno-non-virtual-dtor
  SYMDUMPER                $(NM) -g
  exec_prefix              /usr/local
  bindir                   /usr/local/bin
  sbindir                  /usr/local/sbin
  libexecdir               /usr/local/libexec
  datadir                  /usr/local/share
  sysconfdir               /usr/local/etc
  sharedstatedir           /usr/local/com
  localstatedir            /usr/local/var
  libdir                   /usr/local/lib
  includedir               /usr/local/include
  infodir                  /usr/local/info
  mandir                   /usr/local/man
  BUILT_WITH               GCC GXX OSXLD LIBDL PLUGINS ZLIB HDRHISTOGRAM SNAPPY SOCKEM CRC32C_HW
Generated config.cache

Now type 'make' to build

--- stderr
Building and linking librdkafka statically
Running command: "./configure --disable-sasl --disable-ssl --disable-lz4" in dir: librdkafka
thread 'main' panicked at 'Command failed with error: No such file or directory (os error 2)', build.rs:25:21
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   3: std::panicking::continue_panic_fmt
   4: std::thread::local::fast::Key<T>::try_initialize
   5: build_script_build::run_command_or_fail
             at ./build.rs:25
   6: build_script_build::build_librdkafka
             at ./build.rs:112
   7: build_script_build::main
             at ./build.rs:61
   8: std::rt::lang_start::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
   9: std::panicking::try::do_call
  10: panic_unwind::dwarf::eh::read_encoded_pointer
  11: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
  12: std::rt::lang_start
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  13: build_script_build::make_librdkafka
```

**Comment by benesch** [comment]
This was fixed in #160. Thanks for the report and the initial patch, @a-rodin—super helpful in tracking down the issue!

**Comment by calvinbrown085** [comment]
Did this get released? I'm still running into the same error on MacOS Catalina.

**Comment by benesch** [comment]
Apologies, this is not yet released. You'll have to use the latest master for now.

**Comment by Licenser** [comment]
can we keep the ticket open until it's released? That way people find it as a known problem and don't have to dig through closed issues.

**Comment by benesch** [comment]
Sorry, @Licenser, but GitHub's UI just isn't well set up for that. We'll try to make more frequent releases going forward, though, so that the skew between master and the latest release on crates.io is smaller.
